# Generated by Django 4.2.4 on 2023-10-06 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Produto', max_length=25, verbose_name='Produto')),
                ('tipo', models.CharField(help_text='Tipo do Produto', max_length=25, verbose_name='Tipo')),
                ('valor', models.IntegerField(help_text='Valor do Produto', verbose_name='Valor')),
                ('estoque', models.IntegerField(help_text='Quantia em Estoque', verbose_name='Quantidade')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
