# Generated by Django 4.2.4 on 2023-10-07 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appEcommerce', '0002_alter_products_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Produtos',
        ),
    ]
