# Generated by Django 4.2.4 on 2023-10-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEcommerce', '0003_rename_products_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='valor',
        ),
    ]
