# Generated by Django 4.2.4 on 2023-10-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEcommerce', '0004_remove_produtos_estoque_remove_produtos_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='nome',
            field=models.CharField(default='null', help_text='Nome do Produto', max_length=25, verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='stq',
            field=models.IntegerField(default=0, help_text='Quantia em Estoque', verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='tipo',
            field=models.CharField(default='null', help_text='Tipo do Produto', max_length=25, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='valor',
            field=models.IntegerField(default=0, help_text='Valor do Produto', verbose_name='Valor'),
        ),
    ]
