# Generated by Django 4.2.4 on 2023-11-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEcommerce', '0005_produtos_nome_produtos_stq_produtos_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='owner',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(help_text='Nome do Produto', max_length=25, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='stq',
            field=models.IntegerField(help_text='Estoque do Produto', verbose_name='estoque'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tipo',
            field=models.CharField(help_text='Nome do Produto', max_length=25, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor do Produto', max_digits=10, verbose_name='Valor'),
        ),
    ]
